services:
  api-node:
    command:
      - "npm"
      - "run"
      - "debug-docker"
    ports:
      - "3000:3000"
      # inspect debug port
      - "9229:9229"
  api-golang:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command:
      - "dlv"
      - "debug"
      - "."
      - "--listen=:4000"
      - "--headless=true"
      - "--log=true"
      - "--log-output=debugger,debuglineerr,gdbwire,lldbout,rpc"
      - "--accept-multiclient"
      - "--continue"
      - "--api-version=2"
    ports:
      - "8000:8000"
      # delve debug port
      - "4000:4000"
